### ISSUE TITLE
Unable to parse kml file using ParseKMLIntoFlatFiles.py

### ISSUE THREAD

**Issue by hasnainv** [michaelchughes/satdetect#1]
I have made sure that the path I am entering is correct.
I am running this on 64-bit Linux Mint and an x86_64 architecture.

This is the error message that I am getting:

Traceback (most recent call last):
  File "ParseKMLIntoFlatFiles.py", line 295, in <module>
    Scenes = ReadScenesFromKML(args.kmlfilepath)
  File "ParseKMLIntoFlatFiles.py", line 112, in ReadScenesFromKML
    dom = parseString(xmlstring)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 2

**Comment by michaelchughes** [comment]
Which kml file are you providing as input?  Without knowing the specific file that it's barfing on, it's pretty much impossible to help here.

**Comment by michaelchughes** [comment]
In any case, a recent commit f6709b822e718e07d2fc9c3a4b11504115d1be40 fixed a number of issues with XML parsing to make this script more robust to capitalization issues, extra namespaces, etc. Maybe that fixes the issue

**Comment by hasnainv** [comment]
I tried all KML files. None of them worked. 
I can try again with this commit.
